# Generated by Django 5.2.4 on 2025-07-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_em_portugues', models.CharField(max_length=15)),
                ('chave_em_ingles', models.CharField(max_length=15)),
                ('valor', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=127)),
                ('cargo_em_portugues', models.CharField(max_length=127)),
                ('cargo_em_ingles', models.CharField(max_length=127)),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_portugues', models.TextField()),
                ('em_ingles', models.TextField()),
            ],
        ),
    ]
