# Generated by Django 5.2.4 on 2025-07-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'ordering': ['-nota']},
        ),
        migrations.AddField(
            model_name='competencia',
            name='nota',
            field=models.IntegerField(default=0),
        ),
    ]
